chore: Bump pgbouncer from 1.17.0 to 1.18.0
cloudnative-pg/cloudnative-pg pull request #1201
Opened 2022-12-15 13:19 UTC by PascalBourdier

fix https://github.com/cloudnative-pg/cloudnative-pg/issues/1195

2022-12-15 13:57 UTC, mirakladp approved these changes

2022-12-15 14:26 UTC, sxd commented on docs/src/release_notes/old/v1.15.md
> -  `quay.io/enterprisedb/pgbouncer:1.17.0`
Please do not change the old documentation, it's been kept like that for historical reasons =)

2022-12-15 14:26 UTC, sxd requested changes
Please revert the change in the old release notes

2022-12-15 14:47 UTC, sxd approved these changes

2022-12-15 14:47 UTC, sxd commented
/ok-to-merge

2022-12-15 15:17 UTC, sxd commented
/test feature_type=observability

2022-12-15 16:03 UTC, sxd commented
All the test failed here due to changes in the observability https://github.com/cloudnative-pg/cloudnative-pg/pull/1201

2022-12-16 10:59 UTC, PascalBourdier commented
> All the test failed here due to changes in the observability #1201

@sxd I have updated metric names according this change: https://github.com/pgbouncer/pgbouncer/pull/717

2022-12-16 11:18 UTC, sxd commented
@PascalBourdier let's wait for the test then! :D

2022-12-16 12:27 UTC, sxd commented
@PascalBourdier something else is failing you can check the tests here https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/3712641545

2022-12-16 12:53 UTC, PascalBourdier commented
> @PascalBourdier something else is failing you can check the tests here https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/3712641545

Yes, I see it.
But `cl_active_cancel_req` and `cl_waiting_cancel_req` metrics seem presents:
```
pgbouncer=# SHOW POOLS;
-[ RECORD 1 ]---------+----------
database              | pgbouncer
user                  | pgbouncer
cl_active             | 1
cl_waiting            | 0
cl_active_cancel_req  | 0
cl_waiting_cancel_req | 0
sv_active             | 0
sv_active_cancel      | 0
sv_being_canceled     | 0
sv_idle               | 0
sv_used               | 0
sv_tested             | 0
sv_login              | 0
maxwait               | 0
maxwait_us            | 0
pool_mode             | statement
```

I don't understand why they are not found:
```
  Expected
      <[]string | len:12, cap:20>: [
          "cnpg_pgbouncer_collection_duration_seconds{collector=\"Collect.up\"} 0.00617826",
          "cnpg_pgbouncer_collections_total 1",
          "cnpg_pgbouncer_last_collection_error 0",
          "cnpg_pgbouncer_lists_dns_pending 0",
          "cnpg_pgbouncer_lists_dns_queries 0",
          "cnpg_pgbouncer_lists_free_clients 49",
          "cnpg_pgbouncer_lists_pools 1",
          "cnpg_pgbouncer_lists_used_servers 0",
          "cnpg_pgbouncer_lists_users 2",
          "cnpg_pgbouncer_stats_avg_query_time{database=\"pgbouncer\"} 0",
          "cnpg_pgbouncer_stats_avg_recv{database=\"pgbouncer\"} 0",
          "cnpg_pgbouncer_stats_total_query_count{database=\"pgbouncer\"} 3",
      ]
  to have length 14
```
`cnpg_pgbouncer_pools_pool_mode` seems miss too ...

2022-12-16 12:56 UTC, PascalBourdier commented
Ok, I think https://github.com/cloudnative-pg/pgbouncer-containers should be updated first !

2022-12-20 10:07 UTC, sxd commented
/test feature_type=observability

2022-12-27 10:26 UTC, sxd requested changes
Tests still failing

2022-12-28 15:50 UTC, phisco approved these changes

2022-12-28 15:52 UTC, sxd commented
/test feature_type=observability

2022-12-28 15:52 UTC, phisco commented
/test

2022-12-28 17:36 UTC, phisco commented
/test feature_type=observability

2022-12-28 18:51 UTC, phisco commented
/test feature_type=observability

2022-12-30 20:21 UTC, sxd commented
/test feature_type=observability

2023-01-03 21:44 UTC, sxd approved these changes

2023-01-03 21:44 UTC, sxd commented
/ok-to-merge

2023-02-01 15:09 UTC, phisco commented
/test feature_type=observability

2023-02-01 20:31 UTC, phisco commented
/test

2023-02-02 14:46 UTC, merged