Update grafana-dashboard.json
cloudnative-pg/cloudnative-pg pull request #1916
Opened 2023-04-12 15:24 UTC by itay-grudev

* Improved Cluster Overview
  * Added Last successful base backup
  * Added first recover-ability point
  * Total CPU and memory usage across all nodes
  * Added an Alerts section
* Transposed configuration parameters section
* Volume space and inode usage polystats under the Storage & IO section

**New Cluster Overview**
![image](https://user-images.githubusercontent.com/2123767/231502729-7ab4ee04-af13-4242-beae-65bf8577a2cf.png)

**Transposed configuration parameters**

Before:

![image](https://user-images.githubusercontent.com/2123767/231503161-bbab1d4b-049d-4141-bfa4-75f61a6cdf61.png)

After:

![image](https://user-images.githubusercontent.com/2123767/231503339-d637fbbc-b376-43ea-9d9f-a5f32eeb4d5a.png)

**Storage & IO Space and Inode Usage polystats**
![image](https://user-images.githubusercontent.com/2123767/231503724-f2804c68-5e59-47aa-97e1-cc8ad28ffe15.png)

2023-05-05 16:18 UTC, jsilvela commented
Sorry for the delay. Been deploying this locally.
There is a problem with the datasource references as you have them in your files.

``` json
"datasource": {
        "type": "prometheus",
        "uid": "${DS_PROMETHEUS}"
}
```

These will not work properly with the Grafana as we deploy from the quickstart, using the kube-prometheus-stack.
We can substitute the `"uid"` with `"prometheus"`, as that uid is generated for the data source in the kube-prometheus-stack
deployment.

2023-05-05 16:21 UTC, jsilvela commented
Since the JSON file you generated, in particular, you took from a grafana deployed with a different mechanism, I think there is value in keeping it as-is.
The YAML though, I would like to alter to make sure beginners following the quickstart will get the dashboard working out of the box.
So, I plan to add a bit more context in the documentation, and perhaps fix your files but add your JSON untouched but with a new name.

2023-05-08 07:16 UTC, jsilvela commented
With Itay's latest commit, the dashboard works out of the box if following the `quickstart` document.
Doing a detail review of the panels...

2023-05-08 07:18 UTC, jsilvela commented
@itay-grudev we're seeing errors on missing signoff in one of your commits, could you please fix it?:
> Commit sha: [29c2aed](https://github.com/cloudnative-pg/cloudnative-pg/pull/1916/commits/29c2aedc554d40d2a6ffcfb1dc06a5a59b046d44), Author: Itay Grudev, Committer: Itay Grudev; The sign-off is missing.

2023-05-08 09:57 UTC, jsilvela commented
The JSON/YAML diffs being so large, and their contents being produced, I'll put my comments here, rather than inline.
The `Volume Space Usage` panel is coming up empty in the default installation.

The PromQL is:

```
max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace="$namespace", persistentvolumeclaim=~"$instances"} / kubelet_volume_stats_capacity_bytes{namespace="$namespace", persistentvolumeclaim=~"$instances"}))
```

But those metrics are not available in the kube-prom-stack install and are in ALPHA.
See https://kubernetes.io/docs/reference/instrumentation/metrics/

That said, they don't do damage, and the panel simply won't show much.
We could add some caveats on the `quickstart`, just so beginners are not surprised.

2023-05-08 10:10 UTC, jsilvela commented
As mentioned previously in the volume gauge, the new Storage IO section uses metrics that are in ALPHA, and not available in the kube-prometheus-stack

![Screen Shot 2023-05-08 at 12 09 01](https://user-images.githubusercontent.com/423864/236797623-c3541ffa-f0df-4e06-9165-95268870b6f6.png)

2023-05-08 10:16 UTC, jsilvela requested changes
Brilliant work.
As the diffs are so big (and automated) I have left you comments in the "Conversation" window.
There are some advanced usages you've added that won't work when following the `quickstart` tutorial. My concern is with CloudNativePG beginners being baffled.

I can see two different approaches to get around this:

1. Keep the advanced usages and put a disclaimer on the `quickstart` that some panels won't be visible
2. Remove the advanced features from the ConfigMap, but add them as a new JSON file, with perhaps an `advanced` bit in the filename.

IMO 2 is the better alternative. A step could be added to the quickstart mentioning the advanced features.

2023-05-08 12:16 UTC, gbartolini commented
This is really looking good! Thanks @itay-grudev for the great work! And @jsilvela for the reviews.

2023-05-12 05:47 UTC, benoitschipper commented
Hey all,

Relatively new to contributing, I just wanted to share the following. And again, dismiss me if necessary. We just started using the CNPG Operator on a development cluster. We exposed the metrics and were looking for a dashboard. This dashboard is beautiful so I tested the one coming form this pull Request. After I imported the dashboard using the latest Grafana Operator It loaded the dashboard without problems. Only to find out that it did not show most of the fields, no data. I then found out that the "instances" variable is setup as follows:

**Query:**
```
cnpg_collector_up{namespace=~"$namespace",pod=~"$cluster-.*"}
```
**Regex:**
```
/pod="(?<text>[^"]+)/g
```

I then found that our test CNPG "Cluster" kind of the CPNG Cluster was called "cluster-example". Meaning that my CNPG Cluster related pods or in this case the variables within "instances" did not show, causing the "no data" fields within Grafana. This means that anyone that does not follow the convention of starting their "Cluster" kind name with the "cluster" field will get this problem. 

**My Cluster yaml Snippet:**
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: my-namespace
spec:
…
```

Is this by convention? Or is it a best practice to start your "Cluster" kind name with the name of your kubernetes cluster? 

I was able to fix this by removing the `,pod=~"$cluster-.*"` from the "instance" variable query. Making it so any instance name would show up. The downside being that if you have multiple clusters with the same namespace, you lose the ability to filter on cluster.

**Before:**
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/77777295/24ca8d99-fa2e-43c1-8716-f719e260d11c)

**After:**
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/77777295/870d6a3a-0ed4-4713-8f9b-a3de843c7b68)

Should i simply rename my clusters to start with the clustername? Is there perhaps an alternative to make this Dashboard work with whatever name you give the CNPG Cluster?

I hope this makes sense, thanks in advance!
And thank you for the amazing Dashboard!

2023-05-14 16:04 UTC, itay-grudev commented
@benoitschipper I am having trouble understanding your problem.

The CNPG pods are named: `clusterName-<number>`.
By first selecting the cluster you are monitoring you are populating the `$cluster` variable, which in turn would filter out the pods based on said query:

```
pod=~"$cluster-.*"
```

I have multiple clusters and it's working fine. Maybe the problem is something else, but I'd like to understand what it is.

2023-05-14 16:09 UTC, benoitschipper commented
@itay-grudev I'll check again tomorrow and get back to you. Maybe i misunderstood the scope that was meant with "cluster". For some reason I now think: "Oh they meant CNPG Cluster and not the Kubernetes Cluster. Then again, as you could see, i did get "No Data". I'll check again tomorrow and get back to you :). 

Thanks for getting back to me!

2023-05-15 14:23 UTC, benoitschipper commented
@itay-grudev I think I found the issue here, it has to do with the variables within the Dashboard.

Here the instances variable is depending on the Prometheus, the namespace and the cluster variable. Let met show you the results all the other variables besides instances gives, then it should be clear on why I cannot see my CNPG-Cluster deployment.

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/77777295/7eda4a04-2261-446f-bd63-d6a8bad7afcc)

- DS_PROMETHEUS: prometheus, default
- namespace: venek01-postgresql
- cluster: cd01
- instances: "empty", all

The Prometheus and the namespace variables work fine, but then we get to the cluster variable. And there the variable is populated with the name of my Kubernetes cluster, and not the name of the CNPG-Cluster. As my CNPG-Cluster is called "cluster-example" and as the "instances" variable is filled with the below query + Regex, it does not show any "instances" to monitor within the Dashboard.

**Query:**
`cnpg_collector_up{namespace=~"$namespace",pod=~"$cluster-.*"}`
**Regex:**
`/pod="(?<text>[^"]+)/g`

This because the result of the above query would be:

**Query:**
`cnpg_collector_up{namespace=~"venek01-postgresql",pod=~"cd01-.*"}`

Which would result with or without the regex in 0 hits, as my CNPG-Cluster's name is "cluster-example" and not "cd01-cluster-example".

Due to an additional label called "abcpcluster" (see below), the variable "cluster" is propagated with "cd01" and not with "cluster-example", see below :). The reason this is happening is because we seem to have "externalLabels" fields within our Prometheus setup. One was called "abcpcluster" with a value of "cd01". This key:value is listed within the Prometheus Configuration under "externalLabels" as the people who manage the cluster wanted to add this to all the metrics to be able to easially be able to seperate metrics by Kubernetes or Kubernetes cluster.
![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/77777295/13b24858-0136-49df-96a5-02537a69dffe)

I believe we should be able to prevent this from happening by adjusting the regex that is used within the instances variable to the following `\bcluster\b="(?<text>[^"]+)` . The `\b` denotes a word boundary, ensuring that "cluster" is matched as a whole word and not as part of a larger word. See as demonstrated below:

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/77777295/95ad8ac4-f508-4e58-a859-04c4daaa0024)

That solved the problem for me 😄  Hope this helps! 😃

2023-05-15 15:33 UTC, itay-grudev commented
@benoitschipper Thanks for that. I'll test your proposal and incorporate it into the PR.

2023-05-23 06:56 UTC, sxd commented
@itay-grudev fallowing @jsilvela advice, I think we should add the disclaimer into the quickstart with this PR adding that some features may fails because they need a really new/early version of Grafana.

I'm also adding my self as a reviewer to this PR because I really want to try ti! :D

2023-05-23 07:49 UTC, benoitschipper commented
@sxd ill happily test/review what I can. Already have the dashboard running :)

2023-05-23 08:40 UTC, itay-grudev commented
@sxd I discussed offline with @jsilvela that the alpha metrics are enabled by default on Prometheus. I think it's a limitation of KinD that the volume data is not reported. I've tested it on AWS EKS and Digital Ocean and there it works fine.

I still need to add the change @benoitschipper proposed.

2023-05-23 09:11 UTC, sxd commented
@itay-grudev I've added a warning message that will help users to understand why the graphs doesn't have data, can you review it please! I understand that those are limited in KinD, but lots of users use KinD for testing and at least we need to be nice and put the warning message

2023-05-24 04:27 UTC, benoitschipper commented
> @sxd I discussed offline with @jsilvela that the alpha metrics are enabled by default on Prometheus. I think it's a limitation of KinD that the volume data is not reported. I've tested it on AWS EKS and Digital Ocean and there it works fine.
> 
> I still need to add the change @benoitschipper proposed.

Ill check/review it by testing it as soon as you have added the regex proposal so I can confirm.

2023-05-26 04:26 UTC, benoitschipper approved these changes
@itay-grudev I loaded the Dashboard and went through all the graphs on a live cluster in two seperate clusters. All worked without me making any changes. Works like a charm! 

![image](https://github.com/cloudnative-pg/cloudnative-pg/assets/77777295/75a0ee07-cb46-4a81-ad8b-d20ad3317ce3)

2023-05-26 04:29 UTC, benoitschipper approved these changes

2023-05-26 14:29 UTC, jsilvela approved these changes

2023-05-27 10:27 UTC, sxd approved these changes

2023-05-31 16:09 UTC, merged