feat: adds AWS_DEFAULT_REGION to barman env
cloudnative-pg/cloudnative-pg pull request #207
Opened 2022-05-30 08:59 UTC by armru

Closes #202

2022-05-30 09:00 UTC, armru commented
do not squash

2022-05-31 22:30 UTC, fcanovai requested changes

2022-05-31 22:30 UTC, fcanovai commented on pkg/management/barman/credentials/env.go
> +		return nil, acessKeyErr
```suggestion
	accessKeyID, accessKeyErr := extractValueFromSecret(
		ctx,
		c,
		s3credentials.AccessKeyIDReference,
		namespace,
	)
	if accessKeyErr != nil {
		return nil, accessKeyErr
```

2022-05-31 22:30 UTC, fcanovai commented on pkg/management/barman/credentials/env.go
> +		env = append(env, fmt.Sprintf("AWS_DEFAULT_REGION==%s", region))
```suggestion
		env = append(env, fmt.Sprintf("AWS_DEFAULT_REGION=%s", region))
```

2022-05-31 22:30 UTC, fcanovai commented on api/v1/cluster_types.go
> +
I think it's missing a `make generate`, I do not see anything in the deepcopy file related to this

2022-06-01 10:42 UTC, fcanovai approved these changes

2022-06-03 11:26 UTC, sxd approved these changes

2022-06-03 11:28 UTC, sxd commented
/ok-to-merge

2022-06-03 11:29 UTC, merged