feat: add PhaseReplicaLagThresholdExceeded
cloudnative-pg/cloudnative-pg pull request #2333
Opened 2023-06-20 08:50 UTC by armru

This commit introduces a new phase called PhaseReplicaLagThresholdExceeded. This phase is triggered when one or more replica databases lag beyond a user-defined limit compared to the primary database.

A new `ReplicaLagThreshold` field has been added to the `Cluster` spec, allowing users to define their acceptable replica lag limit. If left unspecified, the operator defaults to a 30MB lag threshold.

Partially Closes #2323

2023-06-20 08:51 UTC, armru commented
/test limit=local

2023-06-20 13:57 UTC, armru commented
/test limit=local

2023-06-20 15:37 UTC, armru commented
/test limit=local

2023-06-21 07:49 UTC, armru commented
/test limit=local

2023-06-21 11:00 UTC, armru commented
/test limit=local

2023-06-22 11:32 UTC, jsilvela requested changes
There's a method added that is not used anywhere - I checked locally that it can be removed and everything is fine.
Wondering if this was meant to use, or is a discarded path, I think this needs to be clarified by the author.

2023-06-22 11:32 UTC, jsilvela commented on pkg/postgres/status.go
> +}
not used anywhere

2023-06-23 07:58 UTC, jsilvela approved these changes

2023-06-26 02:22 UTC, litaocdl commented
/test limit=local

2023-06-27 01:39 UTC, litaocdl commented on api/v1/cluster_types.go
> +	// where 1MB = 1,000,000 Bytes) between the primary database and its replicas. If a replica's lag exceeds this
ReplicaLagThreshold is a user-customizable field that represents the acceptable lag limit (in megabytes... )
========
The default value of the ReplicaLagThreshold is 30,000,000, which is in Bytes, not in megabytes. we should either change the descrption or change the unit used for ReplicaLagThreshold

2023-06-27 04:28 UTC, litaocdl commented
/test limit=local

2023-06-27 04:28 UTC, litaocdl approved these changes

2023-07-04 10:08 UTC, mnencia commented
I've had a meeting with @leonardoce and @armru about this patch. We decided that having a phase that does not change the operator's behavior is pointless. We decided to close this patch without merging, then @armru will open a new PR that will be more complete.

2023-07-04 10:08 UTC, closed without merging