changed the $cluster-.* regex
cloudnative-pg/cloudnative-pg pull request #2412
Opened 2023-07-05 11:22 UTC by smiyc

Fixes #2411

Signed-off-by: Daniel Chambre <smiyc@pm.me>

2023-07-05 11:49 UTC, itay-grudev requested changes

2023-07-05 11:49 UTC, itay-grudev commented on docs/src/samples/monitoring/grafana-configmap.yaml
> +              "expr": "max(cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",pod=~\"$cluster-[0-99]+$\"})",
This Regex is incorrect. Could you replace it with: `-[1-9][0-9]?$`.

Could you replace it in both documents?

2023-07-05 12:06 UTC, itay-grudev commented on docs/src/samples/monitoring/grafana-configmap.yaml
> +              "expr": "max(cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",pod=~\"$cluster-[0-99]+$\"})",
I would also be fine with `-[0-9]+$` for the sake of simplicity.

2023-07-05 14:24 UTC, itay-grudev approved these changes

2023-07-05 18:46 UTC, itay-grudev approved these changes

2023-07-05 19:11 UTC, phisco approved these changes

2023-07-06 13:22 UTC, leonardoce approved these changes

2023-07-06 13:23 UTC, leonardoce commented
/ok-to-merge

2023-07-06 13:29 UTC, merged