Copy edits to samples ad ssl_connections topics
cloudnative-pg/cloudnative-pg pull request #3633
Opened 2023-12-21 19:19 UTC by ebgitelman

2023-12-26 15:43 UTC, jsilvela requested changes
Nice.
There's a sentence I find weird, and I left a GH suggestion.

2023-12-26 15:43 UTC, jsilvela commented on docs/src/ssl_connections.md
> +    content for details on how to use the plugin for kubectl.
this sentence doesn't quite read right

2023-12-26 15:43 UTC, jsilvela commented on docs/src/ssl_connections.md
> +    these values aren't set and continue using the default ones.
```suggestion
    these values aren't set,  and the default ones are used.
```

2023-12-26 17:52 UTC, ebgitelman commented on docs/src/ssl_connections.md
> +    content for details on how to use the plugin for kubectl.
```suggestion
    See the [Certificates in the CloudNativePG plugin](kubectl-plugin.md#certificates)
    content for details on how to use the plugin for kubectl.
```

2023-12-26 17:54 UTC, ebgitelman commented
Thank you for your thorough review!

2023-12-26 17:59 UTC, jsilvela approved these changes

2023-12-26 17:59 UTC, jsilvela commented
thank you!

2024-01-30 16:03 UTC, gbartolini approved these changes

2024-01-30 16:03 UTC, merged