feat: add an option to drop PDBs
cloudnative-pg/cloudnative-pg pull request #3837
Opened 2024-02-19 00:47 UTC by achanda

resolves: #2570

2024-02-19 00:48 UTC, achanda commented
Putting this up for an initial review to make sure this is the right approach. cc @gbartolini 

Things to figure out:
1. Will this affect existing clusters that have this flag changed to false?
2. Tests

2024-02-26 14:37 UTC, gbartolini commented
I think in the longer term we need to understand how this feature will replace for good the `nodeMaintenanceWindow` option. Can you please rename the option `enablePDB`?

I will leave the other maintainers to check whether yours is the right approach on the code. Thanks.

2024-03-05 11:04 UTC, armru commented
/test limit=local

2024-03-05 14:58 UTC, leonardoce approved these changes

2024-03-05 15:06 UTC, leonardoce commented
I agree with the implementation, but I think we should clarify better in the documentation the intersection between the maintenance window stuff and `enablePDB`.

2024-03-06 11:05 UTC, armru approved these changes

2024-03-08 12:43 UTC, pgodowski requested changes

2024-03-08 12:43 UTC, pgodowski commented on config/crd/bases/postgresql.cnpg.io_clusters.yaml
> +              enablePDB:
Please make sure that the new CRD field is also added into the older release (incl 1.18), as per the other discussion about 1.22 and 1.18 CRD compatibility. Thanks!
@mnencia

2024-03-08 15:34 UTC, jsilvela commented on docs/src/kubernetes_upgrade.md
> +prohibits its own draining, safeguarding uninterrupted operations.
IMO this is correct but possibly confusing. The user does have the ability to select a node for draining.
Suggestion
```suggestion
By default, CloudNativePG ensures that if a node to be drained contains the
cluster's primary instance, a switchover happens ahead of the drain. Once the
instance in the node is downgraded to replica, the draining can proceed.
For single-instance clusters, CloudNativePG will prevent draining the node where
the instance is housed, safeguarding operations.
```

2024-03-08 15:48 UTC, jsilvela commented on docs/src/kubernetes_upgrade.md
> +at a time is gracefully shut down during a drain operation.
IMO this is correct but possibly confusing. The user does have the ability to select a node for draining.
Suggestion
```suggestion
By default, CloudNativePG safeguards Postgres cluster operations. If a node is
to be drained and contains a cluster's primary instance, a switchover happens
ahead of the drain. Once the instance in the node is downgraded to replica, the
draining can resume.
For single-instance clusters, a switchover is not possible, so CloudNativePG
will prevent draining the node where the instance is housed.
Additionally, in multi-instance clusters, CloudNativePG guarantees that only
one replica at a time is gracefully shut down during a drain operation.
```

2024-03-08 16:51 UTC, gbartolini commented
I have removed the backport of this functionality to 1.22, but my suggestion is to backport the feature to 1.22 once 1.23.0 is released.

2024-03-08 17:11 UTC, pgodowski commented
> I have removed the backport of this functionality to 1.22, but my suggestion is to backport the feature to 1.22 once 1.23.0 is released.

I am not sure what is the 1.23 timeline, but we're definitely interested in this feature in 1.22.

2024-03-08 20:32 UTC, NiharDudam commented on config/crd/bases/postgresql.cnpg.io_clusters.yaml
> +                default: true
Please move the default values to webhook 

cc: @mnencia

2024-03-11 14:18 UTC, jsilvela commented
I'm not a maintainer...

2024-03-11 14:18 UTC, jsilvela commented
To be honest I don't know how to do it @achanda ... I may ask a maintainer to commit for me...

2024-03-11 14:44 UTC, jsilvela commented
@achanda all figured. I checked out your branch with `gh` as opposed to `git` and had no issue. 🤷 
Going to check a bit and hopefully we merge your patch today!

2024-03-11 14:44 UTC, jsilvela commented
/ready-to-test

2024-03-11 14:54 UTC, jsilvela commented on docs/src/kubernetes_upgrade.md
> +a temporarily degraded cluster may be advisable. This is particularly relevant
"... may be advisable" ... doesn't sound right.
Perhaps I'm misunderstanding. @gbartolini perhaps you meant "acceptable" not "advisable"?

2024-03-11 17:56 UTC, jsilvela commented
/test limit=local feature_type=maintenance

2024-03-12 11:35 UTC, jsilvela commented
/test limit=local feature_type=maintenance

2024-03-12 12:00 UTC, jsilvela approved these changes

2024-03-12 12:01 UTC, jsilvela commented
/ok-to-merge

2024-03-12 14:41 UTC, merged

2024-08-23 09:11 UTC, pgodowski commented
Can I please ask to backport this to 1.22 as well as per earlier comment https://github.com/cloudnative-pg/cloudnative-pg/pull/3837#issuecomment-1986048216 ?

@jsilvela