docs: Release notes for 1.23.1
cloudnative-pg/cloudnative-pg pull request #4401
Opened 2024-04-29 13:22 UTC by leonardoce

Closes: #4400

2024-04-29 13:45 UTC, gbartolini commented on docs/src/release_notes/v1.23.md
> +- Regression preventing the operator from reconciling PodMonitor
```suggestion
- Regression preventing the operator from reconciling `PodMonitor`
```

2024-04-29 13:45 UTC, gbartolini approved these changes

2024-04-29 14:04 UTC, jsilvela requested changes

2024-04-29 14:04 UTC, jsilvela commented on docs/src/release_notes/v1.23.md
> +  resources (#4286)
```suggestion
- Corrects the reconciliation of `PodMonitor` resources, which was
  failing due to a regression (#4286)
```

2024-04-30 08:57 UTC, sxd commented
/ok-to-merge release notes documentation

2024-04-30 09:13 UTC, merged