Main
cloudnative-pg/cloudnative-pg pull request #4960
Opened 2024-06-26 16:14 UTC by smiyc

closes #4957

2024-06-28 15:22 UTC, jsilvela requested changes
The change should work ... however ... sometimes we do see UNIX-style timestamps in the logs.
I think it would be even better if you added an extra paragraph with the original command in case you're getting UNIX timestamps.

2024-06-28 15:23 UTC, jsilvela commented
BTW we should not see UNIX timestamps, but the K8s logging is very messy, so there may be paths that don't do RFC3339...

2024-06-29 14:36 UTC, smiyc reviewed
> BTW we should not see UNIX timestamps, but the K8s logging is very messy, so there may be paths that don't do RFC3339... 

like so?

2024-07-01 07:29 UTC, jsilvela commented on docs/src/troubleshooting.md
> +If the timestamp is displayed in Unix Epoch time, you can convert it to a user-friedgly format:
```suggestion
If the timestamp is displayed in Unix Epoch time, you can convert it to a user-friendly format:
```

2024-07-01 07:30 UTC, jsilvela commented
Exactly like you did (without the typo though ;) )

2024-07-01 07:30 UTC, jsilvela approved these changes

2024-07-01 11:36 UTC, mnencia approved these changes

2024-07-01 11:43 UTC, mnencia commented
/ok-to-merge doc only change

2024-07-01 11:44 UTC, merged