chore: use a proxy to the pod instead of exec a command inside the pod
cloudnative-pg/cloudnative-pg pull request #4974
Opened 2024-06-28 08:46 UTC by sxd

Since the permission `pods/exec` was required and this permission allows users
to execute a command inside a pod, we should instead, do a `pods/proxy` which
only provides a way to proxy data from the pod to the user, avoiding the to have
a permission that will allow users to execute commands inside the pod.

Closes #4941

2024-07-01 16:05 UTC, armru approved these changes

2024-07-02 13:06 UTC, NiccoloFei commented
/test

2024-07-02 18:07 UTC, NiccoloFei approved these changes

2024-07-03 10:19 UTC, mnencia requested changes
This patch breaks the compatibility with old versions of the operator. We need to fix this before merging.

2024-07-03 10:21 UTC, mnencia commented
We need to implement something like we did here https://github.com/cloudnative-pg/cloudnative-pg/commit/692f373da60e4fce0cbd74fe041d5d19ee8b4013#diff-d90e33a455c7ba5834af26c2c0ccf13ecdf069e264f5d1f34d7ac4818bfa7c01R75-R78

2024-07-03 11:49 UTC, mnencia approved these changes

2024-07-03 13:56 UTC, merged