chore: improve OLM environment detection
cloudnative-pg/cloudnative-pg pull request #5031
Opened 2024-07-04 14:33 UTC by sxd

As far as now, we were relying on the detection of the SecurityContextConstraint to know that we were running on an OLM environment but this is not a secure way since an OLM environment may or may not have a SCC inside, that's why we should look at the `operators.coreos.com/v1` resources and check that  it exists, if this is the case, we're in an OLM environment.

This helps us to improve the plugin report and properly retrieve more useful information.

Closes #3764

2024-07-12 08:32 UTC, fcanovai requested changes
Beside the broken piece of code, I'm not convinced about the entire logic.

This PR is checking the `openshift-operators` namespace, and the namespace defined in the plugin call (or `default`). However, it first checks for the operator deployment in the plugin-defined namespace, exiting if the operator is not there. So looking into openshift-operator is not useful, you have to get the operator location right. I think we could just check the namespace asked for in the plugin.

2024-07-12 08:32 UTC, fcanovai commented on internal/cmd/plugin/report/olm.go
> +	return listFromLabelOpenshift, err
This won't merge the lists. If the operator isn't in `openshift-operators`, but we have an operator in a namespace, we return empty list.

2024-07-12 08:32 UTC, fcanovai commented on internal/cmd/plugin/report/olm.go
> +// olmOperatorReport contains the operator data in Oolm
```suggestion
// olmOperatorReport contains the operator data in olm
```

2024-07-15 14:59 UTC, armru approved these changes

2024-07-15 15:02 UTC, armru commented on internal/cmd/plugin/report/olm.go
> +) (client.ObjectList, error) {
Wouldn't make it better to return a []client.object instead of an ObjectList?

2024-07-24 08:28 UTC, fcanovai approved these changes

2024-07-24 08:32 UTC, fcanovai commented
/ok-to-merge

2024-07-24 08:41 UTC, merged