Docs - LDAPConfig/tls description fix
cloudnative-pg/cloudnative-pg pull request #588
Opened 2022-08-12 07:02 UTC by MichaluxPL

2022-08-12 07:25 UTC, gbartolini approved these changes

2022-08-12 07:25 UTC, gbartolini commented on docs/src/api_reference.md
> +`tls           ` | Set to true to enable LDAP over TLS. false is default           | bool
```suggestion
`tls           ` | Set to `true` to enable LDAP over TLS. `false` is default       | bool                                      
```

2022-08-12 08:29 UTC, phisco commented
Hi @MichaluxPL, thanks for your contribution! Unfortunately, that part of the doc is autogenerated, so could you also update the string in the code [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/api/v1/cluster_types.go#L657)?

2022-08-12 08:31 UTC, jsilvela approved these changes

2022-08-12 08:36 UTC, gbartolini commented
@leonardoce rightly hinted that we need to change also `api/v1/cluster_types.go` and then run `make checks` to regenerate the .md file. @MichaluxPL can you please retry?

2022-08-12 08:37 UTC, gbartolini requested changes
Please change api/v1/cluster_types.go file and run make checks to regenerate this file.

2022-08-12 09:28 UTC, MichaluxPL commented
> Please change api/v1/cluster_types.go file and run make checks to regenerate this file.

I've tried to run make checks, but it fails with error:
pkg/configparser/configparser.go:21: File is not `gofmt`-ed with `-s` (gofmt)
1. a struct containing the default values
2. a map from string to strings (e.g. the one that can be extracted for a Kubernetes ConfigMap)
3. an environment source like the system environment variables or a "fake"
   one suitable for testing.
pkg/utils/imagename.go:83: File is not `gofmt`-ed with `-s` (gofmt)
//     GetImageTag("postgres") == "latest"
//     GetImageTag("ghcr.io/cloudnative-pg/postgresql:12.3") == "12.3"
//
pkg/utils/pod_conditions.go:58: File is not `gofmt`-ed with `-s` (gofmt)
// IsPodActive checks if a pod is active, copied from:
controllers/pooler_update.go:57: File is not `gofumpt`-ed (gofumpt)

controllers/pooler_update.go:118: File is not `gofumpt`-ed (gofumpt)

make: *** [Makefile:154: lint] Error 1

2022-08-12 11:45 UTC, jsilvela commented
@MichaluxPL if you do `make apidoc` that should do the changes.

2022-08-12 12:02 UTC, MichaluxPL commented
> @MichaluxPL if you do `make apidoc` that should do the changes.

OK, I've pushed additional changes, You've mentioned.

2022-08-12 13:03 UTC, phisco commented on Makefile
> +	golangci-lint run --timeout 10m0s
please remove this

2022-08-13 06:03 UTC, MichaluxPL commented on Makefile
> +	golangci-lint run --timeout 10m0s
> please remove this

Removed - sorry about that ;)

2022-08-13 09:26 UTC, phisco approved these changes

2022-08-13 09:27 UTC, phisco commented
/ok-to-merge

2022-08-13 12:39 UTC, phisco commented
/ok-to-test

2022-08-13 12:40 UTC, phisco commented
/ready-to-test

2022-08-13 12:43 UTC, sxd approved these changes

2022-08-13 14:59 UTC, phisco approved these changes

2022-08-15 14:19 UTC, jsilvela approved these changes

2022-08-17 15:42 UTC, merged