fix: quote inRoles
cloudnative-pg/cloudnative-pg pull request #6346
Opened 2024-12-18 11:11 UTC by gabriele-wolfox

2024-12-18 13:03 UTC, mnencia requested changes

2024-12-18 13:03 UTC, mnencia commented on internal/management/controller/roles/postgres.go
> +			quotedInRoles[i] = pq.QuoteIdentifier(inRole)
```suggestion
			quotedInRoles[i] = pgx.Identifier{inRole}.Sanitize()
```

2024-12-18 13:04 UTC, mnencia commented on internal/management/controller/roles/postgres.go
> +			quotedInRoles[i] = pq.QuoteIdentifier(inRole)
We don't use `pq.QuoteIdentifier`. All the codebase uses `pgx.Identifier` instead.

2024-12-18 14:48 UTC, mnencia approved these changes

2024-12-18 15:01 UTC, mnencia commented
> @mnencia @gabriele-wolfox this is only for 1.24 right? 1.22 and 1.23 shouldn't be having this PR ?

Declarative role management has been introduced in 1.20, so it needs to be backported to all the branches.

2024-12-19 09:45 UTC, leonardoce commented
I started a few E2e runs on this:

```
STATUS  TITLE              WORKFLOW           BRANCH        EVENT              ID           ELAPSED   AGE
*       continuous-del...  continuous-del...  dev/cnp-5756  workflow_dispatch  12410155110  7s        less than a mi...
*       continuous-del...  continuous-del...  dev/cnp-5756  workflow_dispatch  12410154776  8s        less than a mi...
*       continuous-del...  continuous-del...  dev/cnp-5756  workflow_dispatch  12410154394  10s       less than a mi...
* ```
*

2024-12-19 15:03 UTC, mnencia commented
* https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/12415238247
* https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/12415243728

2024-12-19 15:24 UTC, leonardoce approved these changes

2024-12-19 15:25 UTC, mnencia commented
/ok-to-merge green E2E

2024-12-19 15:35 UTC, merged