fix: version upgrade logic in patch #198 (#330)
cloudnative-pg/cloudnative-pg pull request #720
Opened 2022-09-09 15:25 UTC by armru

This patch cherry-picks the PR containing the logic needed to sanitize the cluster conditions

Closes #719

2022-09-12 23:53 UTC, jlong49 approved these changes

2022-09-19 15:30 UTC, mnencia approved these changes

2022-09-19 15:31 UTC, mnencia commented
/ok-to-merge

2022-09-19 15:31 UTC, danishedb approved these changes

2022-09-19 16:23 UTC, mnencia commented
I just discovered that the condition with the wrong reason is still in the code. We need to fix it before merging.

2022-09-19 16:31 UTC, mnencia requested changes
I just discovered that the condition with the wrong reason is still in the code. We need to fix it before merging.

```
$ git grep -n Reason internal/cmd/manager/walarchive/cmd.go pkg/management/postgres/backup.go
internal/cmd/manager/walarchive/cmd.go:348:                     Reason:  "Continuous Archiving is Failing",
internal/cmd/manager/walarchive/cmd.go:355:             Reason:  "Continuous Archiving is Working",
pkg/management/postgres/backup.go:484:                  Reason:  "Last backup failed",
pkg/management/postgres/backup.go:491:          Reason:  "Last backup succeeded",
```

we need to pick from c2fa5d9fb4e33e0bab9319a54b2018cdec1dfa45 the constants `apiv1.ConditionReasonContinuousArchivingFailing`, `apiv1.ConditionReasonContinuousArchivingSuccess`, `apiv1.ConditionBackupStarted`, `apiv1.ConditionReasonLastBackupFailed`, and `apiv1.ConditionReasonLastBackupSucceeded` and use them to fill the content of the Reason field.

2022-09-19 16:45 UTC, armru commented
The patch should remove the incompatible version set i allowing the user to upgrade to the newer CNPG versions.
I think that modifying the existing conditions on 1.15 could be a different PR

2022-09-19 17:04 UTC, mnencia commented
> The patch should remove the incompatible condition allowing the user to upgrade to the newer CNPG versions. I think that modifying the existing conditions on 1.15 should be in a different PR

The problem is not fixing the existing condition. We continue to add the wrong reasons in the conditions even in this version, then remove the condition immediately after. It is a regression because, after this patch, we will not report any condition in our clusters.

2022-09-20 07:58 UTC, mnencia approved these changes

2022-09-20 07:58 UTC, mnencia commented
/ok-to-merge

2022-09-20 10:18 UTC, merged